<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    <?php

    class LibrosVista {

        // Muestra el listado de todos los libros
        public function mostrarLibros($libros) {
            ?>
            <h1>Listado de Libros</h1>
            
            <h2>Buscar Libro por Título</h2>
            <form action="buscarLibro" method="GET">
                <input type="text" name="titulo_libro" placeholder="Ingrese el título del libro" required>
                <button type="submit">Buscar Libro</button>
            </form>

            <hr>
            <h2>Buscar Autor</h2>
            <form action="buscarAutor" method="GET">
                <input type="text" name="nombre_autor" placeholder="Ingrese nombre o apellido del autor" required>
                <button type="submit">Buscar Autor</button>
            </form>
            <hr>

            <table border="1" cellpadding="5" cellspacing="0">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Autor</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($libros as $libro): ?>
                        <tr>
                            <td><?= htmlspecialchars($libro->titulo) ?></td>
                            <td><?= htmlspecialchars($libro->nombre_autor . ' ' . $libro->apellido_autor)?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php
        }

        // Muestra el detalle de un solo libro
        public function mostrarDetalleLibro($libro) {
            ?>
            <h1>Detalle del Libro: <?= htmlspecialchars($libro->titulo) ?></h1>

            <?php if ($libro): ?>
                <p><strong>Género:</strong> <?= htmlspecialchars($libro->genero) ?></p>
                <p><strong>Año de publicación:</strong> <?= htmlspecialchars($libro->anio_publicacion) ?></p>
                <p><strong>Editorial:</strong> <?= htmlspecialchars($libro->editorial) ?></p>
                <p><strong>Autor:</strong> <?= htmlspecialchars($libro->nombre_autor . ' ' . $libro->apellido_autor) ?></p>
            <?php else: ?>
                <p>No se encontró el libro solicitado.</p>
            <?php endif; ?>
            <?php
        }

        public function mostrarError($mensaje){
            ?>
            <h1>Error</h1>
            <p ><?= htmlspecialchars($mensaje) ?></p>
            <a href="listarLibros">volver al listado</a>
            <?php
        }
    }
    ?>
</body>
</html>