<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php

    function renderForm(){
        echo '
            <h2>Login</h2>
            <form method="POST">
                <input type="text" name="email" placeholder="Ingrese su email..."/>
                <input type="password" name="password" placeholder="Ingrese su password..."/>
                <button>Login</button>
        ';
    }

    //Imprimir el formulario
    renderForm();
    ?>
</body>
</html>